version: '3.6'

networks:
    network:

volumes:
    data:

services:
    postgres: 
        image: postgres
        environment:
            POSTGRES_PASSWORD: password
        networks:
            - 'network'
        volumes:
            - data:/var/lib/postgresql/data

    gochain:
        build:
            context: .
            dockerfile: dockerfile
        depends_on: 
            - postgres
        environment:
            IP: 0.0.0.0
            PORT: 8000
            POSTGRES_URL: postgres
            POSTGRES_PASSWORD: password
        ports:
            - 8000:8000
        networks:
            - 'network'
